"""
Quick test to prove we're calling the REAL API
This will print the actual HTTP requests and responses
"""

import requests

# Enable debug logging to see actual HTTP traffic
import logging
import http.client as http_client

http_client.HTTPConnection.debuglevel = 1

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

print("=" * 60)
print("PROOF: Making REAL API call to http://localhost:8123/transfer")
print("=" * 60)

# Make a real transfer
url = "http://localhost:8123/transfer"
payload = {
    "fromAccount": "ACC1000",
    "toAccount": "ACC1001",
    "amount": 50.00
}

print(f"\nSending POST request to: {url}")
print(f"Payload: {payload}")
print("\n" + "=" * 60)

response = requests.post(url, json=payload)

print("\n" + "=" * 60)
print("RESPONSE FROM REAL SERVER:")
print("=" * 60)
print(f"Status Code: {response.status_code}")
print(f"Response Body: {response.json()}")
print("\nNotice the transaction ID is UNIQUE - generated by YOUR server!")
print("=" * 60)
